/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modelo.AnimalVO;
import servicos.AnimalServicos;

/**
 *
 * @author william
 */
public class UICadAnimal extends javax.swing.JInternalFrame {

    /**
     * Creates new form UICadAnimal
     */
    public UICadAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jpDados = new javax.swing.JPanel();
        jlNomeAnimal = new javax.swing.JLabel();
        jlEspecie = new javax.swing.JLabel();
        jlRaca = new javax.swing.JLabel();
        jlNomeDono = new javax.swing.JLabel();
        jlPeso = new javax.swing.JLabel();
        jlIdade = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jtNomeAnimal = new javax.swing.JTextField();
        jtRaca = new javax.swing.JTextField();
        jtPeso = new javax.swing.JTextField();
        jtNomeDono = new javax.swing.JTextField();
        jtIdade = new javax.swing.JTextField();
        jtEspecie = new javax.swing.JTextField();
        jpAcoes = new javax.swing.JPanel();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);

        jlNomeAnimal.setText("Nome Animal:");

        jlEspecie.setText("Espécie:");

        jlRaca.setText("Raça:");

        jlNomeDono.setText("Dono:");

        jlPeso.setText("Peso:");

        jlIdade.setText("Idade:");

        jlSexo.setText("Sexo:");

        bgSexo.add(jrMasculino);
        jrMasculino.setSelected(true);
        jrMasculino.setText("Masculino");
        jrMasculino.setActionCommand("Masculino");

        bgSexo.add(jrFeminino);
        jrFeminino.setText("Feminino");
        jrFeminino.setActionCommand("Feminino");

        jtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDadosLayout = new javax.swing.GroupLayout(jpDados);
        jpDados.setLayout(jpDadosLayout);
        jpDadosLayout.setHorizontalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlRaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlNomeAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jlPeso))
                        .addGap(18, 18, 18)
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jtNomeAnimal)
                            .addComponent(jtRaca))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEspecie)
                            .addComponent(jlNomeDono)
                            .addComponent(jlIdade))
                        .addGap(18, 18, 18)
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtEspecie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jtNomeDono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtIdade))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addComponent(jlSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrMasculino)
                        .addGap(51, 51, 51)
                        .addComponent(jrFeminino)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpDadosLayout.setVerticalGroup(
            jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDadosLayout.createSequentialGroup()
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNomeAnimal)
                            .addComponent(jlEspecie)
                            .addComponent(jtNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDadosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNomeDono)
                            .addComponent(jtNomeDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlIdade)
                        .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlPeso))
                .addGap(18, 18, 18)
                .addGroup(jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrFeminino)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlSexo)
                        .addComponent(jrMasculino)))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAcoesLayout = new javax.swing.GroupLayout(jpAcoes);
        jpAcoes.setLayout(jpAcoesLayout);
        jpAcoesLayout.setHorizontalGroup(
            jpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAcoesLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jpAcoesLayout.setVerticalGroup(
            jpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar(){
        try {
            AnimalVO aVO = new AnimalVO();
            if(!util.Util.validarNome(jtNomeAnimal.getText())){
                throw new NumberFormatException("Nome do animal invalido!");
            }else{
                aVO.setNomeAnimal(jtNomeAnimal.getText());
            }
            if(!util.Util.validarNome(jtEspecie.getText())){
                throw new NumberFormatException("Nome da especie invalido!");
            }else{
                aVO.setEspecie(jtEspecie.getText());
            }
            if(!util.Util.validarNome(jtRaca.getText())){
                throw new NumberFormatException("nome da raça invalido!");
            }
            else{
                aVO.setRaca(jtRaca.getText());
            }
            if(!util.Util.validarNome(jtNomeDono.getText())){
                throw new NumberFormatException("nome do dono invalido!");
            }else{
                aVO.setNomeDono(jtNomeDono.getText());
            }
            aVO.setSexo(bgSexo.getSelection().getActionCommand());
            if(!util.Util.validarPeso(jtPeso.getText())){
                throw new NumberFormatException("Peso do animal invalido!");
            }else{
                aVO.setPeso(Double.parseDouble(jtPeso.getText()));
            }
            if(!util.Util.validarIdade(jtIdade.getText())){
                throw new NumberFormatException("Idade do animal invalida!");
            }else{
                aVO.setIdade(Integer.parseInt(jtIdade.getText()));
            }
            
            AnimalServicos as = servicos.ServicosFactory.getAnimalServicos();
            
            as.cadastrarAnimal(aVO);
            
            JOptionPane.showMessageDialog(rootPane, "Animal casdastrado com sucesso!");            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Erro " +e.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar! "+e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//fecha cadastrar
    
    private void limpar(){
        jtNomeAnimal.setText("");
        jtEspecie.setText("");
        jtRaca.setText("");
        jtNomeDono.setText("");
        jrMasculino.isSelected();
        jtPeso.setText("");
        jtIdade.setText("");
        
        jtNomeAnimal.grabFocus();
    }//fecha limpar
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlEspecie;
    private javax.swing.JLabel jlIdade;
    private javax.swing.JLabel jlNomeAnimal;
    private javax.swing.JLabel jlNomeDono;
    private javax.swing.JLabel jlPeso;
    private javax.swing.JLabel jlRaca;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JPanel jpAcoes;
    private javax.swing.JPanel jpDados;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JTextField jtEspecie;
    private javax.swing.JTextField jtIdade;
    private javax.swing.JTextField jtNomeAnimal;
    private javax.swing.JTextField jtNomeDono;
    private javax.swing.JTextField jtPeso;
    private javax.swing.JTextField jtRaca;
    // End of variables declaration//GEN-END:variables
}
